name: "deploy to autoupdate endpoint"
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy for'     
        required: true
        default: '0.1.0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch macos sig
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: 'tags/app-v${{ github.event.inputs.version }}'
          file: 'Checkmate.Dev.app.tar.gz.sig'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch linux sig
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: 'tags/app-v${{ github.event.inputs.version }}'
          file: 'checkmate-dev_${{ github.event.inputs.version }}_amd64.AppImage.tar.gz.sig'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch windows sig
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: 'tags/app-v${{ github.event.inputs.version }}'
          file: 'Checkmate.Dev_${{ github.event.inputs.version }}_x64_en-US.msi.zip.sig'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set macos sig
        run: |
              SIG=$(cat Checkmate.Dev.app.tar.gz.sig)\n
              echo "MACOS_SIG=$SIG" >> $GITHUB_ENV

      - name: Set linux sig
        run: |
              SIG=$(cat checkmate-dev_${{ github.event.inputs.version }}_amd64.AppImage.tar.gz.sig)
              echo "LINUX_SIG=$SIG" >> $GITHUB_ENV

      - name: Set windows sig
        run: |
              SIG=$(cat Checkmate.Dev_${{ github.event.inputs.version }}_x64_en-US.msi.zip.sig)\n
              echo "WINDOWS_SIG=$SIG" >> $GITHUB_ENV

      - run: |
              echo "macos: ${{ env.MACOS_SIG }}"
              echo "linux: ${{ env.LINUX_SIG }}"
              echo "windows: ${{ env.WINDOWS_SIG }}"
              echo "windows2: $(cat Checkmate.Dev_${{ github.event.inputs.version }}_x64_en-US.msi.zip.sig)"
